name: suture_eval
description: A web app that evaluate graft suture for vascualr surgeons
# version: 0.0.1
# author: Kazuhiro Miyahara <kazuhiro.miyahara.vs@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  firebase: ^5.0.0
  uuid: ^2.0.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  sass_builder: ^2.1.2
